### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [folixg/kinda-fishy-theme#1]
Please add a screen shot so people can see what the theme looks like.

**Comment by folixg** [comment]
With the amount of themes available I never thought someone would stumble upon mine.
I have added a [README](https://github.com/folixg/kinda-fishy-theme/blob/master/README.md) containing a screenshot.

**Comment by unixorn** [comment]
I maintain the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list, so I look for new ones regularly :-)
